# Generated by Django 4.2.7 on 2026-03-17 10:05

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff')], default='staff', max_length=10)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('gstin', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignment_no', models.CharField(max_length=50, unique=True)),
                ('booking_date', models.DateTimeField()),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('standard', 'Standard'), ('express', 'Express'), ('overnight', 'Overnight')], max_length=20)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('is_manual_cd', models.BooleanField(default=True)),
                ('consignor_name', models.CharField(max_length=200)),
                ('consignor_city', models.CharField(blank=True, max_length=100)),
                ('consignor_address', models.TextField(blank=True)),
                ('consignor_mobile', models.CharField(blank=True, max_length=15)),
                ('consignor_pincode', models.CharField(blank=True, max_length=10)),
                ('consignor_state', models.CharField(blank=True, max_length=100)),
                ('consignee_name', models.CharField(max_length=200)),
                ('consignee_city', models.CharField(blank=True, max_length=100)),
                ('consignee_address', models.TextField(blank=True)),
                ('consignee_mobile', models.CharField(blank=True, max_length=15)),
                ('consignee_state', models.CharField(blank=True, max_length=100)),
                ('total_pieces', models.IntegerField(default=0)),
                ('actual_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('volumetric_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('chargeable_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('invoice_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('ewaybill_no', models.CharField(blank=True, max_length=50)),
                ('product_category', models.CharField(blank=True, max_length=100)),
                ('payment_mode', models.CharField(choices=[('credit', 'Credit'), ('cash', 'Cash'), ('online', 'Online')], default='credit', max_length=20)),
                ('rate_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('freight_amt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fsc_amt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_total_amt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('invoice_currency', models.CharField(default='INR', max_length=10)),
                ('delivery_type', models.CharField(choices=[('door_delivery', 'Door Delivery'), ('pickup', 'Pickup')], default='door_delivery', max_length=20)),
                ('billing_branch', models.CharField(blank=True, max_length=100)),
                ('freight_charge_by', models.CharField(choices=[('consignor', 'Consignor'), ('consignee', 'Consignee')], default='consignor', max_length=20)),
                ('doc_type', models.CharField(choices=[('documents', 'Documents'), ('non_documents', 'Non Documents')], default='non_documents', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.company')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('gstin', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gstin', models.CharField(blank=True, max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.transporter')),
            ],
        ),
        migrations.CreateModel(
            name='EWayBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ewb_number', models.CharField(max_length=50, unique=True)),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('valid_upto', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('delivered', 'Delivered')], default='active', max_length=20)),
                ('hsn_code', models.CharField(blank=True, max_length=20)),
                ('goods_description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('igst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('distance_km', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.consignment')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.transporter')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='consignment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.customer'),
        ),
    ]
