# Generated by Django 4.2.7 on 2026-04-04 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('booked', '📋 Booked'), ('picked_up', '📦 Picked Up'), ('in_transit', '🚛 In Transit'), ('at_hub', '🏭 At Hub / Sorting Centre'), ('out_for_delivery', '🛵 Out for Delivery'), ('delivered', '✅ Delivered'), ('failed_delivery', '❌ Delivery Failed'), ('returned', '↩️ Returned to Sender'), ('cancelled', '🚫 Cancelled'), ('custom', '📝 Custom Update')], default='in_transit', help_text='Select the current shipment stage', max_length=30)),
                ('location', models.CharField(blank=True, help_text='City or location where this update happened (e.g. Chennai Hub)', max_length=200)),
                ('note', models.TextField(blank=True, help_text='Optional extra details (e.g. vehicle number, driver name, reason for delay)')),
                ('timestamp', models.DateTimeField(help_text='Date and time this event happened')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ewb', models.ForeignKey(help_text='Link to the E-Way Bill this update belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='shipment_updates', to='api.ewaybill')),
            ],
            options={
                'verbose_name': 'Shipment Update',
                'verbose_name_plural': 'Shipment Updates',
                'ordering': ['-timestamp'],
            },
        ),
    ]
