# Generated by Django 4.2.7 on 2026-04-04 16:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_shipmentupdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipmentupdate',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='shipmentupdate',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipmentupdate',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentupdate',
            name='ewb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_updates', to='api.ewaybill'),
        ),
        migrations.AlterField(
            model_name='shipmentupdate',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='shipmentupdate',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='shipmentupdate',
            name='status',
            field=models.CharField(choices=[('booked', '📋 Booked'), ('picked_up', '📦 Picked Up'), ('in_transit', '🚛 In Transit'), ('at_hub', '🏭 At Hub / Sorting Centre'), ('out_for_delivery', '🛵 Out for Delivery'), ('delivered', '✅ Delivered'), ('failed_delivery', '❌ Delivery Failed'), ('returned', '↩️ Returned to Sender'), ('cancelled', '🚫 Cancelled'), ('custom', '📝 Custom Update')], default='in_transit', max_length=30),
        ),
        migrations.AlterField(
            model_name='shipmentupdate',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
