# Generated by Django 4.2.7 on 2026-04-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_shipmentupdate_options_shipmentupdate_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAlertConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('recipient_emails', models.TextField(blank=True, default='')),
                ('alert_hours_before', models.IntegerField(default=24)),
                ('send_time', models.CharField(default='08:00', max_length=5)),
                ('include_ewb_details', models.BooleanField(default=True)),
                ('include_goods_details', models.BooleanField(default=False)),
                ('notify_on_cancel', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('last_run_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Email Alert Config',
            },
        ),
    ]
